# Generated by Django 4.2.4 on 2023-10-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tlg_id",
                    models.DecimalField(
                        decimal_places=4, max_digits=25, verbose_name="Телеграм ID"
                    ),
                ),
                (
                    "tlg_contact",
                    models.DecimalField(
                        decimal_places=11, max_digits=15, verbose_name="Номер телефона"
                    ),
                ),
                ("nickname", models.TextField(verbose_name="Имя заказчика")),
            ],
            options={
                "verbose_name": "Заказчик",
                "verbose_name_plural": "Заказчики",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_description", models.TextField(verbose_name="Текст заявки")),
                ("date", models.DateField(verbose_name="Дата публикации")),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_orders.customers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
