# Generated by Django 4.2.4 on 2023-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Подтверждено"),
        ),
    ]
